### ISSUE TITLE
Error installing in Ubuntu 10.10

### ISSUE THREAD

**Issue by skeve** [vrtx64/vk_exaile#3]
There's an error "Plugin archive contains an unsafe path." when trying to install this plugin (0.0.3) in Ubuntu 10.10, Exaile 0.3.2.0

**Comment by skeve** [comment]
ok, it seems that I found the way to solve it:
in ~/.local/share/exaile/plugins/vk_exaile/prefs.py

```
--- prefs.py.orig   2010-05-03 01:59:13.000000000 +0400
+++ prefs.py    2010-08-01 14:02:33.000000000 +0400
@@ -2,13 +2,13 @@

 from xl.nls import gettext as _
 import os
-from xlgui.prefs import widgets
+from xlgui.preferences import widgets

 name = _("Vk_Exaile")
 basedir = os.path.dirname(os.path.realpath(__file__))
 ui = os.path.join(basedir, "preference.ui")

-class PathPreference(widgets.ComboEntryPrefsItem):
+class PathPreference(widgets.ComboEntryPreference):
    name = 'vk_exaile/path'
    preset_items = ["%s/" % os.getenv("HOME")]
    default = "%s/" % os.getenv("HOME")
```

**Comment by vahron** [comment]
- изменить имя функции в **init**.py с get_prefs_pane на get_preferences_pane
- изменить имя панельки в .ui файле с prefs_pane на preferences_pane
- если используются какие-нить еще компоненты, то соотв. образом изменить их имена

**Comment by vrtx64** [comment]
Спасибо) Все никак не обновлюсь до 0.3.2 чтобы протестировать, что они там опять наменяли в SDK. Вечерком доберусь до компа, выложу исправленную версию.

**Comment by vrtx64** [comment]
Судя по первой ошибке проблема была еще в формате архива. Изменения пережал в gz. Все текущие ошибки исправлены. Спасибо!
http://github.com/vrtx64/vk_exaile/commit/e320f5710624bebda8d0a512121534bbea6884ca

**Comment by ubuntupunk** [comment]
Could not load plugin info

Failed plugin: vk_exaile

**Comment by vrtx64** [comment]
какая версия плагина и exaile? когда ошибка появляется?
