### ISSUE TITLE
Всё равное не удается установить: Plugin archive contains an unsafe path.

### ISSUE THREAD

**Issue by petRUShka** [vrtx64/vk_exaile#4]
Установка: vk_exaile_new-0.0.3.exz, Plugin archive contains an unsafe path.

**Comment by vrtx64** [comment]
Версия Exaile?

**Comment by vrtx64** [comment]
vk_exaile_new-0.0.3.exz проверено на нескольких компах с Exaile 0.3.2, загружается корректно.
Если версия Exaile ниже указанной, нужно использовать vk_exaile-0.0.3.exz

**Comment by petRUShka** [comment]
<pre>
$ exaile --version
   ____          _ __    __
  / __/_ _____ _(_) /__ / /
 / _/ \ \ / _ `/ / / -_)_/
/___//_\_\\_,_/_/_/\__(_)   v0.3.2.0
</pre>


<pre>
[petrushka@parch exaile]$ wget http://github.com/downloads/vrtx64/vk_exaile/vk_exaile_new-0.0.3.exz
--2010-08-14 16:23:20--  http://github.com/downloads/vrtx64/vk_exaile/vk_exaile_new-0.0.3.exz
Распознаётся github.com... 207.97.227.239
Устанавливается соединение с github.com|207.97.227.239|:80... соединение установлено.
Запрос HTTP послан, ожидается ответ... 302 Found
Адрес: http://cloud.github.com/downloads/vrtx64/vk_exaile/vk_exaile_new-0.0.3.exz [переход]
--2010-08-14 16:23:24--  http://cloud.github.com/downloads/vrtx64/vk_exaile/vk_exaile_new-0.0.3.exz
Распознаётся cloud.github.com... 216.137.59.159, 216.137.59.214, 216.137.59.11, ...
Устанавливается соединение с cloud.github.com|216.137.59.159|:80... соединение установлено.
Запрос HTTP послан, ожидается ответ... 200 OK
Длина: 52131 (51K) [application/octet-stream]
Saving to: «vk_exaile_new-0.0.3.exz»

100%[====================================================================================================================>] 52 131      29,7K/s   в 1,7s     

2010-08-14 16:23:29 (29,7 KB/s) - «vk_exaile_new-0.0.3.exz» saved [52131/52131]
</pre>


<pre>
[petrushka@parch exaile]$ md5sum vk_exaile_new-0.0.3.exz 
7353324de0d86109690f9e7ddc853275  vk_exaile_new-0.0.3.exz
</pre>


При установке: Plugin archive contains an unsafe path.

**Comment by vrtx64** [comment]
Попробуйте переименовать файл плагина в vk_exaile.exz.
Спасибо за помощь пользователю http://apaxuc.habrahabr.ru/
