### ISSUE TITLE
fail при попытке установи

### ISSUE THREAD

**Issue by cyberflow** [vrtx64/vk_exaile#9]
при попытке поставить плагин пишет:
Plugin archive contains an unsafe path.

Плагин не устанавливается.

Использовался плагин версии 0.0.3 new для exail 0.3.2
Exail версии 0.3.2.2

**Comment by vrtx64** [comment]
Обсуждалось тут https://github.com/vrtx64/vk_exaile/issues/5
Достаточно переименовать файл плагина в vk_exaile.exz
